name: Tests

on:
  merge_group:
    types: [checks_requested]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust build and test
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - name: Install latest stable
        run: rustup update stable
      - name: Install nightly for fmt
        run: rustup install nightly
      - name: Formatting
        run: cargo +nightly fmt --check --verbose
      - name: Build
        run: cargo build --verbose --locked
      - name: Run tests
        run: cargo test --workspace --verbose --locked
